// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © xiaohuihuitrader - original tripple M indicator script
// © emka - modified source code for pullback viewer indicator
// strimaitis.emilis@gmail.com

//@version=4

study("Pullback Viewer by emka", "Pullback Viewer", overlay = true, max_lines_count = 500)

bullish = close > high[1]
bearish = close < low[1]

plotshape(bullish, style=shape.circle, location=location.abovebar, color=#26a69a, size=size.tiny)
plotshape(bearish, style=shape.circle, location=location.belowbar, color=#ef5350, size=size.tiny)
